name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write   # changed to write so we can commit back
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed if you later want to use git commit dates

      # Detect changed markdown files
      - name: Filter changed Markdown files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            markdown:
              - added|modified: '*.md'

      # Update last_modified_at in those files
      - name: Update last_modified_at in changed files
        if: ${{ steps.filter.outputs.markdown == 'true' }}
        run: |
          for file in ${{ steps.filter.outputs.markdown_files }}; do
            echo "Updating $file"
            # Replace existing last_modified_at or insert if missing
            if grep -q '^last_modified_at:' "$file"; then
              sed -i "0,/^last_modified_at:.*/s//last_modified_at: $(date +'%Y-%m-%dT%H:%M:%S%:z')/" "$file"
            else
              sed -i "1ilast_modified_at: $(date +'%Y-%m-%dT%H:%M:%S%:z')" "$file"
            fi
          done

      # Commit the changes back
      - name: Commit changes
        if: ${{ steps.filter.outputs.markdown == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update last_modified_at for modified markdown files"
          branch: ${{ github.ref_name }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
