name: Update Project Visualization URLs

on:
  push:
    branches:
      - main
    paths:
      - '_visualizations/**'
      - 'python/data_entries.py'

permissions:
  contents: write   # Required to push changes

jobs:
  update-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Generate project entries
        run: python python/data_entries.py

      - name: Check for changes
        id: check
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes to main
        if: steps.check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/projects.yml
          git commit -m "Regenerate visualization URLs from data_entries.py"

      - name: Push to main
        if: steps.check.outputs.changed == 'true'
        run: git push origin main
