name: Update Project Visualization URLs

on:
  push:
    paths:
      - '_visualizations/**'
      - 'python/data_entries.py'

permissions:
  contents: write

jobs:
  update-visualizations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install pyyaml

      - run: python python/data_entries.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/projects.yml
          git commit -m "Regenerate _data/projects.yml from _visualizations" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main